### ISSUE TITLE
Using custom TLS certs and Auth Tokens

### ISSUE THREAD

**Issue by ckreiling** [jeffgrunewald/stargate#14]
Hello, I have a couple questions that aren't addressed in the documentation:

Can Stargate communicate over TLS with custom cert paths? And can auth tokens be passed to the client? 

Thank you!

**Comment by jeffgrunewald** [comment]
At the moment, unfortunately no. However, it shouldn’t be too difficult to add since the underlying Websockex client supports both custom ssl configuration via `ssl_options` and passing jwt tokens as `extra_headers`.

I can’t promise 100% that alone will work in Pulsar as the websocket api has the least number of features of all pulsar’s client apis and is the least documented. So I’m sort of trusting their websocket api adheres to standard ssl and token-based auth processes for websockets.

I’ll give it a shot in the next day or so and report back.

**Comment by jeffgrunewald** [comment]
I set up both the producer and the consumer/reader processes init options to construct the necessary flags to pass custom certificates and keys for establishing a TLS connection to a pulsar broker as well as pass a JWT auth token in the header when establishing a connection, per the flags available in Websockex. Let me know if that works and I can cut a new release.

https://github.com/jeffgrunewald/stargate/pull/15

**Comment by ckreiling** [comment]
Hey Jeff, thanks so much for the quick help with this, you rock! I will have to get back to you tomorrow about this. Took a look at the changes and they lgtm, but I'll be testing off of the merged branch tomorrow to see if it works for me

**Comment by ckreiling** [comment]
Submitted a PR instead! Since I saw the places for change

**Comment by ckreiling** [comment]
Hi Jeff, sorry for the radio silence. I have gone ahead and implemented my own client for internal use. The reason I did this is because I wanted to leverage the [Broadway](https://hexdocs.pm/broadway/Broadway.html) library to make consumer acknowledgement much simpler. If it were any other message broker, like Kafka, I wouldn't have taken a crack myself; but the Pulsar websocket API is SO elegant and easy to use. I do, however, want your feedback on my approach!

I made my producers and consumers into a single process each, instead of a few. I notice you have an acknowledger process that's started with each producer websocket process; may I ask why exactly that is? Why not a single process per connection?

In my implementation, I discourage users from directly using the consumer process and instead use the Broadway producer in a Broadway pipeline. The Broadway producer just monitors the websocket process and restarts it when it crashes. What do you think of this design?

**Comment by jeffgrunewald** [comment]
Not to worry. Were you ultimately unsuccessful in getting custom certs and tokens to authenticate against Pulsar? And what underlying websocket or http library do you use to connect to Pulsar?

Stargate is intended to be a general purpose Pulsar client and serve even very high-throughput connections. To that end, both producer and consumer/reader processes offload as much responsibility as possible to free the socket process up to only send and receive packets. This includes the producer acknowledger. Rather than block the websocket process from receiving more messages while the caller is waiting on acknowledgement to unblock, additional messages could be coming and going and the socket remains open. This also allows the caller to explicitly defer to asynchronous acking or forego acking altogether in favor of more speed.

I think Broadway makes sense as an interface to Pulsar and writing the consumer as a broadway producer wouldn't be too difficult. Is your producer implementing the broadway acknowledger behaviour or is the websocket acknowledging received messages immediately as they're entering the broadway pipeline? My only concern there would be dropping messages if there were any failures in processing messages in the broadway handler, those messages would already have been acknowledged to the consumer so they'd be deleted on the Pulsar broker and unavailable to replay. Implementing the broadway acknowledger behaviour ensures that the messages are not acked to the original source (Pulsar in this case) until they've safely been consumed _and_ processed by the consuming application.

**Comment by ckreiling** [comment]
I found it a little difficult to do so, since there are a few modules that need updating and there is a lot of state duplicated across sibling processes (e.g. tenant, topic, namespace). It was also a nice exercise in high-level networks programming with Elixir 😄 I used `WebSockex` as well though since it got me off the ground quicker than a tool like `gun`, and makes writing idiomatic Elixir a little easier.

Ahhh I see, I was wondering if it had to do with the behavior of Pulsar's websocket API. At first glance, the extra acknowledger process seems redundant; it just maintains a map of `message context -> PID` for fetching a PID to notify of an acknowledged message. The only process-blocking call I see in the acknowledger process is the map lookup that takes place [when an acknowledgement message is received](https://github.com/jeffgrunewald/stargate/blob/master/lib/stargate/producer/acknowledger.ex#L67) from Pulsar. Looking up data in a map is very fast, and I have that exact line of code in my producer process's `handle_frame/2` callback impl. The public API for producing has two functions: `async_produce` and `produce`. The `produce` function has a `receive do ...` block that just blocks for the caller, awaiting a success/failure message from the websocket process. `async_produce` is the same, but without the `receive do ...` block; hence it is up to the caller to handle the success or error message when it arrives in its process mailbox.

I think to leverage Elixir's concurrency magic, I want to create a pool of producers with poolboy to increase availability and throughput. What do you think of this idea?

The Broadway producer is separate from the `Broadway.Acknowledger` implementation. It just receives the process name of the Pulsar consumer and calls the `Consumer.acknowledge(consumer, message_id)` function. But this brings up something I haven't thought to ask before but can't find an answer to: can Pulsar messages be acknowledged on a websocket connection they weren't pushed to?

Looking at your public `Consumer` and `Producer` APIs, mine are almost exactly the same. The `Consumer.Handler` behaviour is the exact same, but is called inside the consumer process. This isn't ideal, but I encourage folks in the docs to use the Broadway producer (which implements the `Consumer.Handler` behaviour) instead, and treat the `Consumer` as a more primitive & direct means of interacting with the API.

I also want to say I'm really enjoying this discussion while stuck in quarantine! Thanks for the thoughtful and quick replies.

**Comment by jeffgrunewald** [comment]
Glad to hear it, thanks!

I intended producing to be a blocking process by default until the calling process was notified of success to prevent the producer from sending messages that weren’t being handled. If a producer is spamming messages to the Pulsar broker that aren’t being received, you’d lose those messages. By making produce acknowledge a blocking call, the message has to be successfully handled by Pulsar before it allows you to send any others. You _can_ do asynchronous acking and supply an MFA to have the acknowledger notify some other process that producing the message was successful as well. In either case, that should be on a different process than the websocket connection itself. Hence my separate acknowledger. 

I found websockets to be easy to work with but difficult to work with concurrently since they are single threaded through the one connection. A pool of websocket connections for producing should work but could get more resource intensive than you want since it’s a long-lived connection that needs to be kept alive or times out with inactivity and if message order matters to you that could be difficult to coordinate across your pool. A pool of elixir processes sharing a single websocket connection would be easy but since the traffic is single-threaded through the socket I’m not sure that would buy much. 

Pulsar’s _consumer_ websocket api allows acking in a different connection _if_ you’re in pull mode and sending explicit permit messages, but not for producing that I’ve seen and their documentation is not the best for websockets so I’m not sure how it works.
