### ISSUE TITLE
cannot import this package

### ISSUE THREAD

**Issue by LeeWong** [jeffgrunewald/stargate#3]
after adding stargate to the mix deps, mix deps.get gets the following errors:

Failed to fetch record for 'hexpm/stargate' from registry (using cache instead)
This could be because the package does not exist, it was spelled incorrectly or you don't have permissions to it
** (Mix) No package with name stargate (from: mix.exs) in registry

**Comment by jeffgrunewald** [comment]
Hi Lee,

Thanks so much for your interest; I'm thrilled you'd like to use the package.
Unfortunately it's not quite finished yet so I'm holding off pushing it to Hex until it has a minimally viable producer, reader, and consumer. the producer is, I believe, finished enough. I'd also prefer to write formal tests around the modules rather than the manual testing and validation I've been doing during the development process.

If you'd like to start testing the package (and providing feedback) you can include the Github repo in your mix deps: `{:stargate, github: "jeffgrunewald/stargate"}`. If not, stay tuned,  as I hope to have the official `0.1.0` release out on Hex within the next week.

Cheers!
Jeff

**Comment by jeffgrunewald** [comment]
Side note: I'll leave this issue open until the package is officially published.

**Comment by LeeWong** [comment]
HI Jeff,

You are welcome. Thank you so much for letting me know the current stage of this project. I will start to test out the producer. If I have any feedback, I would be glad to share.   

Thank you for making this project available and looking forward to see more unit tests in the near future.

Cheers,
Lee

**Comment by LeeWong** [comment]
@jeffgrunewald, it might be good to provide some examples on how to use this library.

**Comment by jeffgrunewald** [comment]
The initial release has been completed and published to Hex.
Documentation for the current version of the library is up to date and can be referenced either from the Hex Docs or from the code in Github.

There is quite a bit of functionality I plan to implement in the library over time, but the current release is usable and fully tested as of today.
